Pretrained:
  display_name: "Qwen3-VL-8B-Thinking"
  base_url: "http://localhost:8000/v1/chat/completions"
  model_name: "/public/huggingface-models/Qwen/Qwen3-VL-8B-Thinking"
SFT:
  display_name: "Qwen3-VL-8B-Ours"
  base_url: "http://localhost:8001/v1/chat/completions"
  model_name: "/data/models/Qwen3-VL-8B-Ours"